services:
  mobot:
    image: mobot:latest
    container_name: mobot
    volumes:
      - /mnt/mmc0-4/MoBot/logs:/app/logs
      - /mnt/mmc0-4/MoBot/videos:/app/videos
      - /mnt/mmc0-4/MoBot/config:/app/config
      - /mnt/mmc0-4/MoBot/data:/app/data
      - /mnt/mmc0-4/MoBot/cache:/app/cache
    ports:
      - 5416:5416
    extra_hosts:
      - "bilivekeepheart.lan:192.168.100.1"
      - "chrome.lan:192.168.100.1"
    command:
      - bash
      - -c
      - dotnet MoBot.dll
  mobot_test:
    image: mobot:test
    container_name: mobot_test
    stdin_open: true     # 等价于 docker run -i
    tty: true 
    profiles:
      - test
    volumes:
      - /mnt/mmc0-4/MoBot_Test/logs:/app/logs
      - /mnt/mmc0-4/MoBot_Test/videos:/app/videos
      - /mnt/mmc0-4/MoBot_Test/config:/app/config
      - /mnt/mmc0-4/MoBot_Test/data:/app/data
      - /mnt/mmc0-4/MoBot_Test/cache:/app/cache
    entrypoint:
      - dotnet
      - MoBot.Test.dll
  webshot:
    image: webshot:latest
    container_name: webshot
    ports:
      - 8080:8081
    command:
      - sh
      - -c 
      - nginx -g 'daemon off;' & socat TCP-LISTEN:8081,fork TCP:127.0.0.1:8080
  bilivekeepheart:
    image: bilivekeepheart:latest
    container_name: bilivekeepheart
    ports:
      - 3788:3788
  chrome:
    image: chrome:latest
    container_name: chrome
    ports:
      - 9222:9223
      - 6081:6081
    extra_hosts:
      - "mobot.lan:192.168.100.1"
      - "webshot.lan:192.168.100.1"
    command: 
      - bash
      - -c 
      - /start.sh & socat TCP-LISTEN:9223,fork TCP:127.0.0.1:9222
  mihoyobbs:
    image: womsxd/mihoyo-bbs
    container_name: mihoyobbs
    restart: always
    environment:
      - CRON_SIGNIN=30 9 * * *
      - MULTI=TRUE
    volumes:
      - /mnt/mmc0-4/MihoyoBBSTools/config:/var/app/config
      - /mnt/mmc0-4/MihoyoBBSTools/push.py:/var/app/push.py
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
